name: sweeping-triplet
method: bayes
metric:
  name: train/loss
  goal: minimize
parameters:
  model_architecture:
    values: ['TripletModel', 'EfficientNet', 'FusionModel']
  wildlife_name:
    values: ['whaleshark', 'raptors']
  batch_size:
    values: [64, 128]
  embedding_size:
    values: [768]
  triplet_loss:
    parameters:
      margin:
        values: [0.5]
      mining_type:
        values: ['semihard'] 
  solver:
    parameters:
      BASE_LR:
        values: [0.0001, 0.001, 0.005]
      LR_SCHEDULER:
        values: ['step', 'reduce_on_plateau']

