name: arcface-tuning-alllvls
method: grid 
metric:
  name: val/mAP
  goal: maximize

parameters:
  preprocess_lvl:
    values: [2, 3, 4, 5]

  seed:
    values: [42, 1234, 7]

  embedding_size:
    values: [256]

  arcface_loss.margin:
    values: [0.3, 0.4, 0.5]

  arcface_loss.scale:
    values: [30, 50, 64]
