name: arcface-refinement-large
method: bayes
metric:
  name: val/mAP
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 6
parameters:
  preprocess_lvl:
    values: [2]
  embedding_size:
    values: [256]
  arcface_loss.margin:
    values: [0.5]
  arcface_loss.scale:
    values: [64]
  solver.lr_max:
    values: [0.001]