name: sweeping-arcface
method: bayes
metric:
  name: val/mAP5
  goal: maximize
early_terminate:
  type: hyperband
  min_iter: 5
parameters:
  arcface_loss:
    parameters:
      margin:
        min: 0.3
        max: 0.6
      scale:
        min: 32
        max: 128