name: sweeping-bayes-raptor-triplet
run_cap: 20
method: bayes
metric:
  name: val/mAP
  goal: maximize
parameters:
  triplet_loss:
    parameters:
      margin:
        distribution: uniform
        min: 0.3
        max: 0.7
      mining_type:
        values: ['semihard', 'hard']
  arcface_loss:
    parameters:
      margin:
        distribution: uniform
        min: 0.2
        max: 0.5
      scale:
        distribution: uniform
        min: 20
        max: 40
  solver:
    parameters:
      LR_SCHEDULER:
        values: ['reduce_on_plateau', 'cosine_annealing']
      lr_max:
        distribution: log_uniform_values
        min: 1e-5
        max: 1e-3
      lr_start:
        distribution: log_uniform_values
        min: 1e-6
        max: 1e-4
      lr_ramp_ep:
        values: [5, 8, 10]
      WEIGHT_DECAY:
        distribution: log_uniform_values
        min: 1e-4
        max: 1e-2
      lr_min:  # Only for cosine_annealing
        distribution: log_uniform_values
        min: 1e-6
        max: 1e-5
early_terminate:
  type: hyperband
  min_iter: 5
  eta: 3