name: sweeping-triplet
method: grid
metric:
  name: val/mAP
  goal: maximize
parameters:
  batch_size:
    values: [32, 64, 128]
  embedding_size:
    values: [128, 256, 512, 768, 2048]
  triplet_loss:
    parameters:
      margin:
        values: [0.2, 0.5, 0.7]
      mining_type:
        values: ['semihard', 'hard'] 
  solver:
    parameters:
      BASE_LR:
        values: [0.0001, 0.001, 0.005]
      LR_SCHEDULER:
        values: ['step', 'reduce_on_plateau']

