name: sweeping-arcface
method: grid
metric:
  name: train/loss_epoch
  goal: minimize
parameters:
  arcface_loss:
    parameters:
      margin:
        values: [0.3, 0.5]
      scale:
        values: [32,50,64]