name: finetune-single-lvl
method: grid 
metric:
  name: val/mAP
  goal: maximize

parameters:
  seed:
    values: [42, 1234]

  use_gradcam: 
    values: [False]
  val_viz: 
    values: [False]

  batch_size:
    values: [64, 128, 256]

  embedding_size:
    values: [256, 512]

  solver.BASE_LR:
    values: [0.001, 0.002]
