name: arcface-lite-sweep
method: grid 
metric:
  name: val/mAP
  goal: maximize

parameters:
  preprocess_lvl:
    values: [2, 3, 4, 5]

  seed:
    values: [42, 1234, 7]

  embedding_size:
    values: [256]

  solver.lr_max:
    distribution: log_uniform_values
    min: 1e-5
    max: 5e-3


  arcface_loss.margin:
    values: [0.3, 0.4, 0.5]

  arcface_loss.scale:
    values: [30, 50, 64]
