name: sweeping-arcface
method: grid
metric:
  name: train/loss_epoch
  goal: minimize
parameters:
  model_architecture:
    values:
  wildlife_name:
    values: 
  batch_size:
    values:
  embedding_size:
    values: 
  triplet_loss:
    parameters:
      margin:
        values:
      mining_type:
        values: 
  arcface_loss:
    parameters:
      margin:
        values: [0.3, 0.5]
      scale:
        values: [32,50,64]
  solver:
    parameters:
      BASE_LR:
        values: 
      LR_SCHEDULER:
        values: 

