project_name: eagleID
notes: 
use_wandb: False
wandb_entity: winniethepooh

annot_dir: 
annot_train_file:
annot_val_file: 
annot_test_file: 


outdir: 
dataset: ../datasets/raptor_individuals_cropped
split_ratio: 0.8
cache_path: dataset/dataframe/cache.csv

backbone_name: resnet50
model_architecture: TripletModel
checkpoint: 
preprocess_lvl: 3

batch_size: 4
img_size: 256
epochs: 150
save_interval: 10
n_gpu: 1
num_workers: 2
gpu_ids: 
seed: 42

use_gradcam: True

transforms:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

triplet_loss:
  embedding_size: 128
  margin: 0.2
  mining_type: semihard
  distance_matrix: euclidean

early_stopping:
  monitor: val/loss
  min_delta: 0.0005
  patience: 50
  verbose: true
  mode: min

solver:
  OPT: adam  # adam, sgd
  WEIGHT_DECAY: 0.001
  MOMENTUM: 0.9  # only when OPT is sgd
  BASE_LR: 0.0001
  LR_SCHEDULER: reduce_on_plateau  # step, multistep, reduce_on_plateau
  LR_DECAY_RATE: 0.1
  LR_STEP_SIZE: 10  # only when LR_SCHEDULER is step
  LR_STEP_MILESTONES: [10, 15]  # only when LR_SCHEDULER is multistep

re_ranking: True