name: sweeping-triplet
method: grid
metric:
  name: train/loss
  goal: minimize
parameters:
  model_architecture:
    values: ['EfficientNet', 'FusionModel']
  wildlife_name:
    values: ['whaleshark', 'raptors']
  batch_size:
    values: [64, 128]
  embedding_size:
    values: [128, 768]
  triplet_loss:
    parameters:
      margin:
        values: [0.5]
      mining_type:
        values: ['semihard'] 
  arcface_loss:
    parameters:
      margin:
        values: [0.25, 0.5]
      scale:
        values: [32,64]
  solver:
    parameters:
      BASE_LR:
        values: [0.0001, 0.001, 0.005]
      LR_SCHEDULER:
        values: ['step', 'reduce_on_plateau']

