project_name: age-classifier-local
notes: 
use_wandb: False
wandb_entity: winniethepooh

annot_dir: ./dataset/annot/
annot_train_file: final_train_sep_sightings.csv
annot_val_file: final_val_sep_sightings.csv
annot_test_file: 


outdir: ./results
dataset: /Users/amee/Desktop/artportalen_goeag

model_name: resnet50
model_architecture: SimpleModel
checkpoint: 
preprocess_lvl: 3
batch_size: 4
img_size: 128
epochs: 100
save_interval: 10
n_gpu: 1
num_workers: 1
gpu_ids: 
seed: 42

use_gradcam: True

transforms:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

early_stopping:
  monitor: val/loss
  min_delta: 0.0005
  patience: 10
  verbose: true
  mode: min

solver:
  OPT: adam  # adam, sgd
  WEIGHT_DECAY: 0.0001
  MOMENTUM: 0.9  # only when OPT is sgd
  BASE_LR: 0.001
  LR_SCHEDULER: step  # step, multistep, reduce_on_plateau
  LR_DECAY_RATE: 0.1
  LR_STEP_SIZE: 10  # only when LR_SCHEDULER is step
  LR_STEP_MILESTONES: [10, 15]  # only when LR_SCHEDULER is multistep
