name: arcface-tuning-alllvls
method: grid 
metric:
  name: val/mAP
  goal: maximize

parameters:
  preprocess_lvl:
    values: [4,5]

  seed:
    values: [42, 1234]

  embedding_size:
    values: [256]

  arcface_loss.margin:
    values: [0.3,0.4]

  arcface_loss.scale:
    values: [30,50]
