name: finetune-single-lvl
method: grid 
metric:
  name: val/mAP
  goal: maximize

parameters:
  seed:
    values: [42, 1234]

  use_gradcam: 
    values: [False]
  val_viz: 
    values: [False]

  arcface_loss.margin:
    values: [0.3, 0.5]
  arcface_loss.scale:
    values: [50, 30]